# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://github.com/codecov/example-node

language: "node_js"
node_js:
- "6"
- "8"
install:
- "npm install"
os:
- "linux"
- "osx"
branches:
  only:
  - "master"
  - "develop"
  - /^v\d/
cache:
  directories:
  - "node_modules"
script:
- "npm run verify"
deploy:
  provider: "npm"
  on:
    tags: true
  email:
    secure: "sBFKf7wm0CYAP6gxyXCddme0UnmmOqyLczADZgQIDYWf7YAiqEKTC5rBC1+2qqBG1VHA8q6UbE7L8M2JPSrQxmqsc2lCwyOL3h/tKf8QYjrd3bSjCH5ogaWGu7DJHvBGbkuJ+iCrIYhKhAlYZoOuxushdrYx9Gp1OlNEabUdpCpljsmgN1EX3zYJiyqUIeL7HbFHqMlNl7n/+i18W7Uji0Ybos+8o+fMayEZmSer0vc9cT+8nSIMDvxnAhHaMCQb/CWR+s/ZST1dFpV0xrONmt6m0qC6t+hr2dfhmaUdgPh9bJQDxS7MS/7f43z+0ArevFJY300d4crTCsVV60hWF64u133yiGj8vnYKc5ZgpVGBNyOPiMP/BtQMOHomC1fUWYRn0aroWMuERZw1cRcv19XJ47HejNYTapyD7MqeHVnAEhugfeMxjAXRJFVnLkoN/qmhiZcrK5oaBmlIi0BHHPw2zQZSoBEGqZav2+Hb1xohMY1TMXZ7KVRJf9WeoOsLhw+6I2k5LYyNYuTVDuY6B5zDmXED02mYrhAwWBYYhB4UfWG0muddv8nnaXRXQV+DDXDuDWeBvgR37MzQonoapC88V2MPjaehnFOhXNtUAw2NnxA1OJRiKEcEHoSgVr/vPtuilTInmYIpVct9mQREtJNefDt3r1h7quDFmy5lK9Q="
  api_key:
    secure: "f9OY2OQSnutn+yAe9pSE8k6W9TuclGpMyEQ7XVqf4GolSqG0LsK3IVN9QmDXcFiT2+Gx56/fiBT+yHE93Nk0lvIpPltCvWZylAhuzbPbFNoeV4hPTRITAxaw1c05FDUKGd3dmJh5dRQ2VAykGoTqbXWcHECR/S0LTD/wIKDJ4RJnSOORfV16+zLsiAVge2V9HA59s0g15wIKbM8fboV2D6HqK51v6XMGl7nvCh+/iA1KVySkOkzAgbLcJeF+q2Gd0Z8vc6qEqbgCLrOHdtvCac0N088msl4GAxxpdTS+Cf0yIio7prTlmcACjbgtJOEfIiJkwq0hJ8p7tVv7Z2//IaML1dCm3SDi4IZwTX3q0EsLTkOjWcYD/43nk5SBZgyfuzHLlP4i6JLrFW0SVm3fq1j0lPWkjKPH5RLpfl+szU2Ziipv22PgTCRqdm0alNiYgMyLmQ7ZVpMH2DNGuaLBqrcQ4MS0GkjAO+EwZ7HDiZrMEJk1jexNbMHJTOcvEzMCLRKnVboGLdWe3iF4krkmC6yNCpcFpmgqLFgNKydHUOqn1kX3RFgdOkABqfnEI0FqFedrPph3mVsCLlSzxbrL44t2GZ+fvQ6N3A5JrUC3CFLPFlgKhmigiEghAyTBoVcPcgVIgDVpaOZKiLrCqqm6MAhkR7k9X1hyyzqTSvCrhyc="
