# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: pull_request
name: Code Coverage
jobs:
  code-coverage:
    name: Report Code Coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        nodejs:
        - 12
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Update global packages
      run: npm i -g node-gyp
    - name: Install dependencies
      run: npm i
    - name: Verify
      run: npm run verify
    - name: Report code coverage
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
